name: Website do Mateus
description: Dicas e tutoriais em Python, C++, Lua e Go
meta_description: "Website do Mateus, Dicas e tutoriais em Python, C++, Lua e Go"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://mateusmb.github.io'
google_analytics: 'UA-105693738-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://mateusmb.github.io'
author:         'Mateus Moraes Bueno'
